language: haskell

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libgtk2.0-dev libgtk-3-dev
  - sudo apt-get build-dep -qq gtk2hs-buildtools
  - cabal install gtk2hs-buildtools

ghc:
  - 7.0
  - 7.4
  - 7.6
  - 7.8
